---
title: "Use of the prefix /bu/, /bɯ/"
date: 2026-01-20
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: tango
    css: styles.css
---


```{r setup, echo=FALSE, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  fig.height = 5, fig.width = 6)

library(tidyverse)
library(RColorBrewer)
library(leaflet)
library(leaflet.minicharts)
library(lingtypology)
library(DT)

setwd("D:/Учёба/Фарси/tajik-dialect-atlas")
```

::: {{.panel-tabset}}

```{r echo=FALSE, include=FALSE}
features <- read_delim("data/features.csv",
                       delim = ",", show_col_types = FALSE)
features <- drop_na(features, "value_eng")

dialects <- read_delim("data/features_dialects.csv",
                       delim = ",", show_col_types = FALSE)
names(dialects)[names(dialects) == "value_orig"] <- "dialect_orig"
names(dialects)[names(dialects) == "value_rus"] <- "dialect_rus"
names(dialects)[names(dialects) == "value_eng"] <- "dialect_eng"

dialects <- dialects[c("settlement_id",
           "dialect_orig", "dialect_rus", "dialect_eng",
           "group_orig", "group_rus", "group_eng")]

coordinates <- read_delim("data/coordinates.csv",
                          delim = ",", show_col_types = FALSE)
coordinates <- left_join(coordinates, dialects)
features <- left_join(features, coordinates)

feature_data <- features |> filter(feature_id == 6)
```

```{r echo=FALSE, include=FALSE}

# SORTING AND FACTORING

sort_smart <- function(tbl, col) {
  col <- dplyr::enquo(col)

  tbl %>%
    mutate(
      .sort_key = case_when(
        is.na(!!col) ~ 2L,
        !!col == "no data" ~ 2L,
        TRUE ~ 1L
      )
    ) %>%
    arrange(.sort_key, !!col) %>%
    select(-.sort_key)
}

feature_data <- feature_data |> sort_smart(value_eng)

feature_values <- unique(feature_data$value_eng)

feature_data$feature_orig <- factor(feature_data$feature_orig)
feature_data$feature_rus <- factor(feature_data$feature_rus)
feature_data$feature_eng <- factor(feature_data$feature_eng)

feature_data$value_orig <- factor(feature_data$value_orig)
feature_data$value_rus <- factor(feature_data$value_rus)
feature_data$value_eng <- factor(feature_data$value_eng)
```

```{r echo=FALSE, include=FALSE}
palette_set <- "Set1"

value_palette <- colorFactor(
  palette = palette_set,
  domain = feature_values
)
value_colors <- value_palette(feature_values)
value_colors[feature_values %in% c("no data", "нет данных")] <- "lightgray"
```

### Map

```{r}
minichart_data <- feature_data %>%
  count(number, value_eng) %>%
  sort_smart(value_eng) %>%
  pivot_wider(
    names_from = value_eng,
    values_from = n,
    values_fill = 0
  ) %>%
  arrange(number)

coordinates.current <- coordinates %>%
  filter(number %in% minichart_data$number)

x <- feature_data %>%
  group_by(number) %>%
  summarise(
    values = paste(unique(value_eng),
                   collapse = ', '),
    .groups = "drop")
coordinates.current$values <- x$values
rm(x)

coordinates.current$html_popup <- str_c(
  "<b>", coordinates.current$settlement_name_official_full, "</b><br>",
  "name in the original source: ", coordinates.current$settlement_name_rastorgueva, "<br>",
  "modern country: ", coordinates.current$country_modern, "<br>",
  "coordinates: ", coordinates.current$lat, ", ",
  coordinates.current$lon, "<br><br>",
  "dialect: ", coordinates.current$dialect_eng, "<br>",
  "dialect group: ", coordinates.current$group_eng, "<br><br>",
  "values: ", coordinates.current$values
)
  
map <- leaflet(feature_data) %>%
  addTiles() %>%
  leaflet.minicharts::addMinicharts(
    coordinates.current$lon,
    coordinates.current$lat,
    type = "pie",
    chartdata = minichart_data[, -1],
    colorPalette = value_colors,
    width = 16,
    opacity = 1,
    legendPosition="bottomleft") %>%
  addCircleMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "villages",
    label = coordinates.current$settlement_name_official_full,
    labelOptions = labelOptions(textsize = "12px"),
    popup = coordinates.current$html_popup,
    fillColor = "white",
    fillOpacity = 0,
    opacity = 0,
    radius = 8) %>%
  addLabelOnlyMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "numbers",
    label = coordinates.current$settlement_id,
    labelOptions = labelOptions(
      noHide = TRUE, textOnly = TRUE,
      direction = "left", offset = c(-10, 1.7),
      style = list("font-size" = "14px"))
  ) %>%
  addLabelOnlyMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "names",
    label = coordinates.current$settlement_name_official,
    labelOptions = labelOptions(
      noHide = TRUE, textOnly = TRUE,
      direction = "right", offset = c(10, 1.7),
      style = list("font-size" = "14px"))
  ) %>%
  addLayersControl(
    overlayGroups = c("numbers", "names"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("numbers") %>%
  hideGroup("names")
map
```

### Data

```{r}
names(coordinates.current)[names(coordinates.current) == "settlement_name_rastorgueva"] <- "name (orig.)"
names(coordinates.current)[names(coordinates.current) == "settlement_name_official_full"] <- "name (modern)"
DT::datatable(coordinates.current %>%
                arrange(number) %>%
                select(
                  `name (orig.)`,
                  `name (modern)`,
                  lat, lon,
                  values), 
              class = "cell-border stripe",
              rownames = FALSE,
              filter = "top",
              options = list(pageLength = 10, 
                           autoWidth = TRUE,
                           info = FALSE))
```

