---
title: "Употребление формы с istodan в изъявительном наклонении"
date: 2025-12-15
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: tango
    css: styles.css
---


```{r setup, echo=FALSE, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  fig.height = 5, fig.width = 6)

library(tidyverse)
library(RColorBrewer)
library(leaflet)
library(leaflet.minicharts)
library(lingtypology)
library(DT)

setwd("D:/Учёба/Фарси/tajik dialect atlas/github")
```

::: {{.panel-tabset}}

```{r echo=FALSE, include=FALSE}
features <- read_delim("data/features.csv",
                       delim = ",", show_col_types = FALSE)
features <- drop_na(features, "value")
features$feature_rus <- as.factor(features$feature_rus)

coordinates <- read_delim("data/coordinates.csv",
                          delim = ",", show_col_types = FALSE)
features <- left_join(features, coordinates)

palette_set <- "Set1"

feature_data <- features |> filter(feature_id == 12)
feature_values <- sort(unique(feature_data$value))

lang_palette <- colorFactor(
  palette = palette_set, domain = feature_values)
```

### Map

```{r}
minichart_data <- feature_data %>%
  count(settlement_id, value) %>%
  pivot_wider(
    names_from = value,
    values_from = n,
    values_fill = 0
  ) %>%
  arrange(settlement_id)

feature_coordinates <- coordinates %>%
  filter(settlement_id %in% minichart_data$settlement_id)

feature_values_by_settlement <- feature_data %>%
  group_by(settlement_id) %>%
  summarise(
    values = paste(unique(value),
                   collapse = '", "'),
    .groups = "drop")
feature_coordinates$values <- str_c(
  '"', feature_values_by_settlement$values, '"')

feature_coordinates$html_popup <- str_c(
  "<b>", feature_coordinates$settlement_name_rastorgueva, "</b><br>",
  "modern name: ", feature_coordinates$settlement_name_official, "<br>",
  "modern country: ", feature_coordinates$country_modern, "<br>",
  "coordinates: ", feature_coordinates$lat, ", ",
  feature_coordinates$lon, "<br><br>",
  "values: ", feature_coordinates$values
)
  
map <- leaflet(feature_data) %>%
  addTiles() %>%
  leaflet.minicharts::addMinicharts(
    feature_coordinates$lon,
    feature_coordinates$lat,
    type = "pie",
    chartdata = minichart_data[, -1],
    #colorPalette = lang_palette(feature_values),
    #popup = leaflet.minicharts::popupArgs(
    #  html = feature_coordinates$html_popup),
    width = 16,
    opacity = 1,
    legendPosition="bottomleft") %>%
  addCircleMarkers(
    feature_coordinates$lon, feature_coordinates$lat,
    group = "villages",
    label = feature_coordinates$settlement_name_rastorgueva,
    labelOptions = labelOptions(textsize = "12px"),
    popup = feature_coordinates$html_popup,
    fillColor = "white",
    fillOpacity = 0,
    opacity = 0,
    radius = 8) -> map
map
```

### Data

```{r}
DT::datatable(feature_coordinates %>%
                select(
                  settlement_name_rastorgueva,
                  settlement_name_official,
                  lat, lon,
                  values), 
              class = "cell-border stripe",
              rownames = FALSE,
              filter = "top",
              options = list(pageLength = 10, 
                           autoWidth = TRUE,
                           info = FALSE))
```

