---
title: "Dialect groups"
date: 2026-03-05
bibliography: data/bib.bib
link-citations: TRUE
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: tango
    css: styles.css
---


```{r setup, echo=FALSE, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  fig.height = 5, fig.width = 6)

library(tidyverse)
library(RColorBrewer)
library(leaflet)
library(leaflet.minicharts)
library(lingtypology)
library(DT)

setwd("D:/Учёба/Фарси/tajik-dialect-atlas")
```

::: {{.panel-tabset}}

```{r echo=FALSE, include=FALSE}
features <- read_delim("data/features_dialects.csv",
                       delim = ",", show_col_types = FALSE)
features <- drop_na(features, "value_eng")

coordinates <- read_delim("data/coordinates.csv",
                          delim = ",", show_col_types = FALSE)
features <- left_join(features, coordinates)

feature_data <- features |> filter(feature_id == 18)
```

```{r echo=FALSE, include=FALSE}

# SORTING AND FACTORING

sort_smart <- function(tbl, col) {
  col <- dplyr::enquo(col)

  tbl %>%
    mutate(
      .sort_key = case_when(
        is.na(!!col) ~ 2L,
        !!col == "no data" ~ 2L,
        TRUE ~ 1L
      )
    ) %>%
    arrange(.sort_key, !!col) %>%
    select(-.sort_key)
}

feature_data <- feature_data |> sort_smart(group_eng)

feature_values <- unique(feature_data$value_eng)
feature_groups <- unique(feature_data$group_eng)

feature_data$feature_orig <- factor(feature_data$feature_orig)
feature_data$feature_rus <- factor(feature_data$feature_rus)
feature_data$feature_eng <- factor(feature_data$feature_eng)

feature_data$value_orig <- factor(feature_data$value_orig)
feature_data$value_rus <- factor(feature_data$value_rus)
feature_data$value_eng <- factor(feature_data$value_eng)

feature_data$group_orig <- factor(feature_data$group_orig)
feature_data$group_rus <- factor(feature_data$group_rus)
feature_data$group_eng <- factor(feature_data$group_eng)
```

```{r echo=FALSE, include=FALSE}
default_palette <- c(
  "#5FC857FF",
  "#F06F4AFF",
  "#E0D64DFF",
  "#6F88DCFF",
  "#FA8FC0FF",
  "#7CCFDEFF",
  "#F2AE2BFF",
  "#B95BCFFF",
  "#B8A754FF"
)

#additional_palette <- c("#CF4E9CFF", "#8C57A2FF", "#355DB9FF", "#82581FFF", "#2F709EFF", "#E5614CFF", "#97A1A7FF", "#3DA873FF", "#DC9445FF")
```

### Map

```{r}
minichart_data <- feature_data %>%
  count(number, group_eng) %>%
  sort_smart(group_eng) %>%
  pivot_wider(
    names_from = group_eng,
    values_from = n,
    values_fill = 0
  ) %>%
  arrange(number)

coordinates.current <- coordinates %>%
  filter(number %in% minichart_data$number)

x <- feature_data %>%
  group_by(number) %>%
  summarise(
    values = paste(unique(value_eng),
                   collapse = '", "'),
    .groups = "drop")
coordinates.current$values <- x$values
x <- feature_data %>%
  group_by(number) %>%
  summarise(
    groups = paste(unique(group_eng),
                   collapse = '", "'),
    .groups = "drop")
coordinates.current$groups <- x$groups
rm(x)

coordinates.current$values_quoted <- str_c(
  '"', coordinates.current$values, '"')

coordinates.current$html_popup <- str_c(
  "<b>", coordinates.current$settlement_name_official_full, "</b><br>",
  "name in the original source: ", coordinates.current$settlement_name_rastorgueva, "<br>",
  "modern country: ", coordinates.current$country_modern, "<br>",
  "coordinates: ", coordinates.current$lat, ", ",
  coordinates.current$lon, "<br><br>",
  "dialect: ", coordinates.current$values, "<br>",
  "dialect group: ", coordinates.current$groups
)
coordinates.current$value_color <- arrange(
  feature_data, number)$value_color
coordinates.current$group_color <- arrange(
  feature_data, number)$group_color

map <- leaflet(feature_data) %>%
  addTiles() %>%
  
  # VISIBLE CIRCLE MARKERS FOR DIALECT VALUES
  addCircleMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "dialects",
    label = coordinates.current$settlement_name_official_full,
    labelOptions = labelOptions(textsize = "12px"),
    color = coordinates.current$value_color,
    fillOpacity = 100,
    opacity = 0,
    radius = 12) %>%
  
  # VISIBLE MINICHART MARKERS FOR GROUP VALUES
  addCircleMarkers(
    coordinates.current$lon, coordinates.current$lat,
    fillColor = coordinates.current$group_color,
    fillOpacity = 100,
    radius = 8,
    opacity = 0) %>%
  
  # INVISIBLE CIRCLE MARKERS FOR POPUP
  addCircleMarkers(
    coordinates.current$lon, coordinates.current$lat,
    label = coordinates.current$settlement_name_official_full,
    labelOptions = labelOptions(textsize = "14px"),
    popup = coordinates.current$html_popup,
    fillColor = "white",
    fillOpacity = 0,
    opacity = 0,
    radius = 12) %>%
  
  # VILLAGE NUMBERS
  addLabelOnlyMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "numbers",
    label = coordinates.current$settlement_id,
    labelOptions = labelOptions(
      noHide = TRUE, textOnly = TRUE,
      direction = "center", offset = c(0, -1),
      style = list("font-size" = "14px"))
  ) %>%
  
  # VILLAGE NAMES
  addLabelOnlyMarkers(
    coordinates.current$lon, coordinates.current$lat,
    group = "names",
    label = coordinates.current$settlement_name_official,
    labelOptions = labelOptions(
      noHide = TRUE, textOnly = TRUE,
      direction = "right", offset = c(13, -1),
      style = list("font-size" = "14px"))
  ) %>%
  addLayersControl(
    overlayGroups = c("numbers", "names"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("numbers") %>%
  hideGroup("names")
map
```

### Data

```{r}
names(coordinates.current)[names(coordinates.current) == "settlement_name_rastorgueva"] <- "name (orig.)"
names(coordinates.current)[names(coordinates.current) == "settlement_name_official_full"] <- "name (modern)"
names(coordinates.current)[names(coordinates.current) == "values"] <- "dialect"
names(coordinates.current)[names(coordinates.current) == "groups"] <- "dialect group"

DT::datatable(coordinates.current %>%
                arrange(number) %>%
                select(
                  `name (orig.)`,
                  `name (modern)`,
                  lat, lon,
                  `dialect`,
                  `dialect group`), 
              class = "cell-border stripe",
              rownames = FALSE,
              filter = "top",
              options = list(pageLength = 10, 
                           autoWidth = TRUE,
                           info = FALSE))
```

